<?xml version="1.0" encoding="ASCII"?>
<Artifact:Artifact xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Artifact="http://documentum.emc.com/infrastructure/12012007/artifact" xmlns:moduledef="http://documentum.emc.com/artifact/12012007/moduledef" urn="urn:com.emc.ide.artifact.moduledef/px-numberservice-sbo?artifactURI=file:/Users/markdav/dev/projectx/composer-projects/projectx-sbo/Artifacts/Modules/px-numberservice-sbo.module" categoryId="com.emc.ide.artifact.moduledef">
  <dataModel xsi:type="moduledef:ModuleDef" objectName="org.markdav.projectx.bof.numberservice.api.INumberService" contact_info="Mark Davidson" a_module_type="SBO" module_description="SBO for generating numbers">
    <objectType href="urn:com.emc.ide.artifact.dclass/dmc_module?name=dmc_module#//@dataModel"/>
    <interfaceJars href="urn:com.emc.ide.artifact.jardef.jardef/px-numberservice-api?artifactURI=file:/Users/markdav/dev/projectx/composer-projects/projectx-sbo/Artifacts/JAR%20Definitions/px-numberservice-api.jardef#//@dataModel"/>
    <implementationJars href="urn:com.emc.ide.artifact.jardef.jardef/px-numberservice-impl?artifactURI=file:/Users/markdav/dev/projectx/composer-projects/projectx-sbo/Artifacts/JAR%20Definitions/px-numberservice-impl.jardef#//@dataModel"/>
    <runtimeEnvironmentXML objectName="RuntimeEnvironment.xml">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_sysobject?name=dm_sysobject#//@dataModel"/>
      <log/>
    </runtimeEnvironmentXML>
    <primaryElement primary_class="org.markdav.projectx.bof.numberservice.impl.NumberService">
      <a_interfaces>org.markdav.projectx.bof.numberservice.api.INumberService</a_interfaces>
      <a_interfaces>com.documentum.fc.client.IDfService</a_interfaces>
      <a_interfaces>com.documentum.fc.client.IDfModule</a_interfaces>
    </primaryElement>
    <miscellaneous objectName="Miscellaneous">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_folder?name=dm_folder#//@dataModel"/>
    </miscellaneous>
  </dataModel>
  <viewModel xsi:type="Artifact:DefaultArtifactViewModel"/>
</Artifact:Artifact>
